### Manipulating models to make them able to grow in community

In [ ]:
with warnings.catch_warnings():
    warnings.filterwarnings('ignore')

    model1 = reframed.load_cbmodel("../models/species_used/Bacteroides_ovatus_ATCC_8483.xml")
    model2 = reframed.load_cbmodel("../models/species_used/Bacteroides_thetaiotaomicron_VPI_5482.xml")

In [ ]:
import copy

**Adding transport and metabolites for sink reactions**

In [ ]:
for model_i in [model1,model2]:
    sink_reactions = [rxn for rxn in model_i.get_exchange_reactions() if "sink" in rxn]
    extra_reactions = ["R_pbiosynthesis","R_rtranscription","R_dreplication"]
    
    sink_reactions.extend(extra_reactions)
    for rxn in sink_reactions:
        if rxn in extra_reactions:
            met_c_id = model_i.reactions[rxn].get_products()[0]
        else:
            met_c_id = model_i.reactions[rxn].get_substrates()[0]

        met_e_id = copy.copy(met_c_id)
        met_e_id = met_e_id.replace("_c_","_e_")
        met_e = reframed.Metabolite(met_e_id,model_i.metabolites[met_c_id].name,compartment=model_i.compartments.e.id)

        model_i.add_metabolite(met_e)
        model_i.add_reaction_from_str(f"R_{met_c_id[2:-13]}_sink: {met_c_id} <-> {met_e_id}")

        print(model_i.reactions[f"R_{met_c_id[2:-13]}_sink"])

R_s_sink: M_s__91__c__93__ <-> M_s__91__e__93__
R_thissh_sink: M_thissh__91__c__93__ <-> M_thissh__91__e__93__
R_proteinsynth_sink: M_proteinsynth__91__c__93__ <-> M_proteinsynth__91__e__93__
R_rnatrans_sink: M_rnatrans__91__c__93__ <-> M_rnatrans__91__e__93__
R_dnarep_sink: M_dnarep__91__c__93__ <-> M_dnarep__91__e__93__
R_gthrd_sink: M_gthrd__91__c__93__ <-> M_gthrd__91__e__93__
R_s_sink: M_s__91__c__93__ <-> M_s__91__e__93__
R_thissh_sink: M_thissh__91__c__93__ <-> M_thissh__91__e__93__
R_proteinsynth_sink: M_proteinsynth__91__c__93__ <-> M_proteinsynth__91__e__93__
R_rnatrans_sink: M_rnatrans__91__c__93__ <-> M_rnatrans__91__e__93__
R_dnarep_sink: M_dnarep__91__c__93__ <-> M_dnarep__91__e__93__

In [ ]:
model1.reactions.R_pbiosynthesis

R_pbiosynthesis:  --> M_proteinsynth__91__c__93__

**Adding transport and metabolites for demand reactions**

In [ ]:
for model_i in [model1,model2]:
    for rxn in [rxn for rxn in model_i.get_exchange_reactions() if "R_DM" in rxn]:
        if "R_DM_atp_c" in rxn:
            continue
            
        print(model_i.reactions[rxn])
        met_c_id = model_i.reactions[rxn].get_substrates()[0]

        met_e_id = copy.copy(met_c_id)
        met_e_id = met_e_id.replace("_c_","_e_")
        met_e = reframed.Metabolite(met_e_id,model_i.metabolites[met_c_id].name,compartment=model_i.compartments.e.id)
        model_i.add_metabolite(met_e)
        
        model_i.add_reaction_from_str(f"R_{met_c_id[2:-13]}_DM: {met_c_id} --> {met_e_id}")
        print(model_i.reactions[f"R_{met_c_id[2:-13]}_DM"])
    
    model_i.update()

R_DM_2HYMEPH: M_2hymeph__91__c__93__ -->
R_2hymeph_DM: M_2hymeph__91__c__93__ --> M_2hymeph__91__e__93__
R_DM_4HBA: M_4hba__91__c__93__ -->
R_4hba_DM: M_4hba__91__c__93__ --> M_4hba__91__e__93__
R_DM_AMOB: M_amob__91__c__93__ -->
R_amob_DM: M_amob__91__c__93__ --> M_amob__91__e__93__
R_DM_adocbl__40__c__41__: M_adocbl__91__c__93__ -->
R_adocbl_DM: M_adocbl__91__c__93__ --> M_adocbl__91__e__93__
R_DM_btn: M_btn__91__c__93__ -->
R_btn_DM: M_btn__91__c__93__ --> M_btn__91__e__93__
R_DM_dad_5: M_dad_5__91__c__93__ -->
R_dad_5_DM: M_dad_5__91__c__93__ --> M_dad_5__91__e__93__
R_DM_kdo2lipid4L__40__c__41__: M_kdo2lipid4L__91__c__93__ -->
R_kdo2lipid4L_DM: M_kdo2lipid4L__91__c__93__ --> M_kdo2lipid4L__91__e__93__
R_DM_pheme__40__c__41__: M_pheme__91__c__93__ -->
R_pheme_DM: M_pheme__91__c__93__ --> M_pheme__91__e__93__
R_DM_this__91__c__93__: M_this__91__c__93__ -->
R_this_DM: M_this__91__c__93__ --> M_this__91__e__93__
R_DM_4HBA: M_4hba__91__c__93__ -->
R_4hba_DM: M_4hba__91__c__93__ --> M_4hba__91__e__93__
R_DM_5MTR: M_5mtr__91__c__93__ -->
R_5mtr_DM: M_5mtr__91__c__93__ --> M_5mtr__91__e__93__
R_DM_AMOB: M_amob__91__c__93__ -->
R_amob_DM: M_amob__91__c__93__ --> M_amob__91__e__93__
R_DM_btn: M_btn__91__c__93__ -->
R_btn_DM: M_btn__91__c__93__ --> M_btn__91__e__93__
R_DM_clpn180__40__c__41__: M_clpn180__91__c__93__ -->
R_clpn180_DM: M_clpn180__91__c__93__ --> M_clpn180__91__e__93__
R_DM_clpnai17__40__c__41__: M_clpnai17__91__c__93__ -->
R_clpnai17_DM: M_clpnai17__91__c__93__ --> M_clpnai17__91__e__93__
R_DM_clpni17__40__c__41__: M_clpni17__91__c__93__ -->
R_clpni17_DM: M_clpni17__91__c__93__ --> M_clpni17__91__e__93__
R_DM_dad_5: M_dad_5__91__c__93__ -->
R_dad_5_DM: M_dad_5__91__c__93__ --> M_dad_5__91__e__93__
R_DM_kdo2lipid4L__40__c__41__: M_kdo2lipid4L__91__c__93__ -->
R_kdo2lipid4L_DM: M_kdo2lipid4L__91__c__93__ --> M_kdo2lipid4L__91__e__93__
R_DM_teich_45_BS__40__c__41__: M_teich_45_BS__91__c__93__ -->
R_teich_45_BS_DM: M_teich_45_BS__91__c__93__ --> M_teich_45_BS__91__e__93__
R_DM_this__91__c__93__: M_this__91__c__93__ -->
R_this_DM: M_this__91__c__93__ --> M_this__91__e__93__

In [ ]:
model1.reactions.R_biomass536.stoichiometry.pop("M_biomass__91__c__93__")

1.0

In [ ]:
model2.reactions.R_biomass345.stoichiometry.pop("M_biomass__91__c__93__")

1.0

#### Remove demand reactions and add new exchange reactions

In [ ]:
for model_i in [model1,model2]:
    dm_replace = [rxn for rxn in model_i.get_exchange_reactions() if "R_DM" in rxn]
    for rxn in dm_replace:
        if "R_DM_atp_c" in rxn:
            continue
        
        print(model_i.reactions[rxn].get_substrates()[0])
        met_c_id = model_i.reactions[rxn].get_substrates()[0]
        met_e_id = copy.copy(met_c_id)
        met_e_id = met_e_id.replace("_c_","_e_")
        
        reaction = reframed.CBReaction("R_EX_"+met_e_id[2:],stoichiometry = {met_e_id:-1},reversible=False,reaction_type=reframed.ReactionType.EXCHANGE)
        model_i.add_reaction(reaction)
        model_i.remove_reaction(rxn)
        #model_i.add_reaction_from_str(f"R_{met_c_id[2:-13]}_DM: {met_c_id} --> {met_e_id}")

M_2hymeph__91__c__93__
M_4hba__91__c__93__
M_amob__91__c__93__
M_adocbl__91__c__93__
M_btn__91__c__93__
M_dad_5__91__c__93__
M_kdo2lipid4L__91__c__93__
M_pheme__91__c__93__
M_this__91__c__93__
M_4hba__91__c__93__
M_5mtr__91__c__93__
M_amob__91__c__93__
M_btn__91__c__93__
M_clpn180__91__c__93__
M_clpnai17__91__c__93__
M_clpni17__91__c__93__
M_dad_5__91__c__93__
M_kdo2lipid4L__91__c__93__
M_teich_45_BS__91__c__93__
M_this__91__c__93__

#### Remove sink reactions and add new exchange reactions

In [ ]:
for model_i in [model1,model2]:
    
    sink_reactions = [rxn for rxn in model_i.get_exchange_reactions() if "sink" in rxn]
    extra_reactions = ["R_pbiosynthesis","R_rtranscription","R_dreplication"]
    
    sink_reactions.extend(extra_reactions)
    for rxn in sink_reactions:
        if rxn in extra_reactions:
            met_c_id = model_i.reactions[rxn].get_products()[0]
        else:
            met_c_id = model_i.reactions[rxn].get_substrates()[0]
       
        met_e_id = copy.copy(met_c_id)
        met_e_id = met_e_id.replace("_c_","_e_")
        
        reaction = reframed.CBReaction("R_EX_"+met_e_id[2:],stoichiometry = {met_e_id:-1},reversible=True,reaction_type=reframed.ReactionType.EXCHANGE)
        model_i.add_reaction(reaction)
        print(reaction)
        model_i.remove_reaction(rxn)
        #model_i.add_reaction_from_str(f"R_{met_c_id[2:-13]}_DM: {met_c_id} --> {met_e_id}")

R_EX_s__91__e__93__: M_s__91__e__93__ <->
R_EX_thissh__91__e__93__: M_thissh__91__e__93__ <->
R_EX_proteinsynth__91__e__93__: M_proteinsynth__91__e__93__ <->
R_EX_rnatrans__91__e__93__: M_rnatrans__91__e__93__ <->
R_EX_dnarep__91__e__93__: M_dnarep__91__e__93__ <->
R_EX_gthrd__91__e__93__: M_gthrd__91__e__93__ <->
R_EX_s__91__e__93__: M_s__91__e__93__ <->
R_EX_thissh__91__e__93__: M_thissh__91__e__93__ <->
R_EX_proteinsynth__91__e__93__: M_proteinsynth__91__e__93__ <->
R_EX_rnatrans__91__e__93__: M_rnatrans__91__e__93__ <->
R_EX_dnarep__91__e__93__: M_dnarep__91__e__93__ <->

In [ ]:
model1.update()
model2.update()

In [ ]:
reframed.save_cbmodel(model1,f"../models/manipulated_models/{model1.id}.xml")
reframed.save_cbmodel(model2,f"../models/manipulated_models/{model2.id}.xml")

#### Test the growth of the individual models

In [ ]:
env = reframed.Environment.from_reactions(lb_ex_rxns_old)

env.apply(model1, inplace=True, exclusive=True, warning=False)

sol = reframed.pFBA(model1)

In [ ]:
lb_ex_rxns_old[0]

'R_EX_adn__40__e__41__'

In [ ]:
sol.values["R_biomass536"]

0.0

In [ ]:
env.apply(model2, inplace=True, exclusive=True, warning=False)

sol = reframed.pFBA(model2)

In [ ]:
model2.biomass_reaction

'R_biomass345'

In [ ]:
sol.values["R_biomass345"]

0.0

In [ ]:
test_lb = list(copy.copy(lb_ex_rxns_old))

In [ ]:
test_lb.append("R_EX_thissh__91__e__93__")
test_lb.append("R_EX_gthrd__91__e__93__")
test_lb.append("R_EX_s__91__e__93__")
test_lb.append("R_EX_proteinsynth__91__e__93__")
test_lb.append("R_EX_rnatrans__91__e__93__")
test_lb.append("R_EX_dnarep__91__e__93__")

In [ ]:
env2= reframed.Environment.from_reactions(test_lb)
env2.apply(model1, inplace=True, exclusive=True, warning=False)
sol = reframed.pFBA(model1)

In [ ]:
sol.values["R_biomass536"]

2.0976637499932598

In [ ]:
env2.apply(model2, inplace=True, exclusive=True, warning=False)

sol = reframed.pFBA(model2)

In [ ]:
sol.values["R_biomass345"]

2.134772368679991

#### Test growth in community

In [ ]:
lb_ex_rxns.append("R_EX_thissh__91__e__93__")
lb_ex_rxns.append("R_EX_gthrd__91__e__93__")
lb_ex_rxns.append("R_EX_s__91__e__93__")
lb_ex_rxns.append("R_EX_proteinsynth__91__e__93__")
lb_ex_rxns.append("R_EX_rnatrans__91__e__93__")
lb_ex_rxns.append("R_EX_dnarep__91__e__93__")

In [ ]:
comm = reframed.Community("test",[model1,model2],copy_models=True)

env = reframed.Environment.from_reactions(lb_ex_rxns)
env.apply(comm.merged_model, inplace=True, exclusive=True, warning=False)

sol = reframed.pFBA(comm.merged_model)

In [ ]:
sol.values["community_growth"]

2.159784218927665

#### Finding blocked reactions

**In not manipulated model**

In [ ]:
with warnings.catch_warnings():
    warnings.filterwarnings('ignore')

    model1_n = reframed.load_cbmodel("../models/species_used/Bacteroides_ovatus_ATCC_8483.xml")
    model2_n = reframed.load_cbmodel("../models/species_used/Bacteroides_thetaiotaomicron_VPI_5482.xml")

In [ ]:
comm2 = reframed.Community("test",[model1_n,model2_n],copy_models=True)

env_complete.apply(comm2.merged_model, inplace=True, exclusive=True, warning=False)

In [ ]:
met_one_reaction = []
for met in comm2.merged_model.metabolites:
    rxns = comm2.merged_model.get_metabolite_reactions(met)
    if len(rxns)==1:
        met_one_reaction.append(rxns[0])

In [ ]:
sol = reframed.FVA(comm2.merged_model,obj_frac=0)

/Users/idunmariaburgos/opt/anaconda3/envs/rcell_rec/lib/python3.8/site-packages/reframed/cobra/variability.py:56: UserWarning: Infeasible solution status
  warn('Infeasible solution status')
/Users/idunmariaburgos/opt/anaconda3/envs/rcell_rec/lib/python3.8/site-packages/reframed/cobra/variability.py:58: UserWarning: Unknown solution status
  warn('Unknown solution status')
/Users/idunmariaburgos/opt/anaconda3/envs/rcell_rec/lib/python3.8/site-packages/reframed/cobra/variability.py:76: UserWarning: Unknown solution status
  warn('Unknown solution status')
/Users/idunmariaburgos/opt/anaconda3/envs/rcell_rec/lib/python3.8/site-packages/reframed/cobra/variability.py:74: UserWarning: Infeasible solution status
  warn('Infeasible solution status')

In [ ]:
none_reactions = [rxn for rxn,value in sol.items() if (value[0] is None) or (value[1] is None)]

In [ ]:
new_sol = {rxn:value for rxn,value in sol.items() if rxn not in none_reactions}

blocked_reactions = [rxn for rxn,value in new_sol.items() if ((abs(value[0])<1e-6) and (abs(value[1])<1e-6))]

In [ ]:
len(blocked_reactions)+len(none_reactions)

1330

In [ ]:
len(met_one_reaction)

503

In [ ]:
len(set(met_one_reaction).intersection(set(blocked_reactions)))

399

In [ ]:
len(set(met_one_reaction).intersection(set(none_reactions)))

14

In [ ]:
len(none_reactions)

131

In [ ]:
len(comm2.merged_model.reactions)

4802

**In manipulated model**

In [ ]:
met_one_reaction = []
for met in comm.merged_model.metabolites:
    rxns = comm.merged_model.get_metabolite_reactions(met)
    if len(rxns)==1:
        met_one_reaction.append(rxns[0])

In [ ]:
sol = reframed.FVA(comm.merged_model,obj_frac=0)

In [ ]:
none_reactions = [rxn for rxn,value in sol.items() if (value[0] is None) or (value[1] is None)]

In [ ]:
new_sol = {rxn:value for rxn,value in sol.items() if rxn not in none_reactions}

blocked_reactions = [rxn for rxn,value in new_sol.items() if ((abs(value[0])<1e-6) and (abs(value[1])<1e-6))]

In [ ]:
len(blocked_reactions)+len(none_reactions)

1137

In [ ]:
len(met_one_reaction)

489

In [ ]:
len(set(met_one_reaction).intersection(set(blocked_reactions)))

397

In [ ]:
len(set(met_one_reaction).intersection(set(none_reactions)))

7

In [ ]:
len(comm.merged_model.reactions)

4842

#### Find rxns also blocked in individual models

In [ ]:
env_complete_m1 = reframed.Environment.complete(model1).apply(model1,inplace=True,exclusive=True)
env_complete_m2 = reframed.Environment.complete(model2).apply(model2,inplace=True,exclusive=True)

In [ ]:
sol_m1 = reframed.FVA(model1,obj_frac=0)
sol_m2 = reframed.FVA(model2,obj_frac=0)

In [ ]:
model1.id

'M_Bacteroides_ovatus_ATCC_8483'

In [ ]:
model2.id

'M_Bacteroides_thetaiotaomicron_VPI_5482'

In [ ]:
sol_m1_new = {rxn+"_"+model1.id:values for rxn,values in sol_m1.items()}
sol_m2_new = {rxn+"_"+model2.id:values for rxn,values in sol_m2.items()}
sol_m1_m2 = {**sol_m1_new,**sol_m2_new}

In [ ]:
sol_m1_m2_s = pd.Series(sol_m1_m2)
sol_m1_m2_s.name = "m1+m2"

In [ ]:
sol_merged_s = pd.Series(sol)
sol_merged_s.name = "merged"

In [ ]:
combined_df = pd.concat([sol_m1_m2_s,sol_merged_s],axis=1)

combined_df.dropna(inplace=True)
combined_df

,m1+m2,merged
R_12PPD_Stex_M_Bacteroides_ovatus_ATCC_8483,"[-2770.0, 0.0]","[-2770.0, 0.0]"
R_12PPDtpp_M_Bacteroides_ovatus_ATCC_8483,"[-2770.0, 0.0]","[-2770.0, 0.0]"
R_1HIBUPGLU_St2pp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[0.0, 10.0]"
R_1HIBUPGLU_Stex_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[0.0, 10.0]"
R_1HIBUP_S_GLCAASE_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[0.0, 10.0]"
...,...,...
R_clpni17_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 9.99999999998844]","[0.0, 9.999999999999954]"
R_dad_5_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 10.0]","[0.0, 10.0]"
R_kdo2lipid4L_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 10.000000000132715]","[0.0, 10.000000000000268]"
R_teich_45_BS_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.4444444444534992]","[0.0, 0.4444444444444452]"
R_this_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.0678878737432866]","[0.0, 0.0]"

In [ ]:
blocked_or_none = copy.copy(blocked_reactions)
blocked_or_none.extend(none_reactions)

In [ ]:
different_sol_df =  combined_df[combined_df["m1+m2"]!=combined_df["merged"]]

different_sol_df = different_sol_df[different_sol_df.index.isin(blocked_or_none)]
different_sol_df.head(30)

,m1+m2,merged
R_2OBUTtex_M_Bacteroides_ovatus_ATCC_8483,"[-1681171.4705882382, 10.0]","[None, 10.0]"
R_2OH_CBZ_GLC_GLCAASE_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_CBZ_GLC_GLCAASEepp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_CBZ_GLCt2pp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_CBZ_GLCtex_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_CBZtepp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_CBZtex_M_Bacteroides_ovatus_ATCC_8483,"[-10.0, 0.0]","[None, 0.0]"
R_2OH_MTZ_GLC_GLCAASE_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_MTZ_GLC_GLCAASEepp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_MTZ_GLCt2pp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_MTZ_GLCtex_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_MTZtepp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 10.0]","[None, 10.0]"
R_2OH_MTZtex_M_Bacteroides_ovatus_ATCC_8483,"[-10.0, 0.0]","[None, 0.0]"
R_2OMFUCtex_M_Bacteroides_ovatus_ATCC_8483,"[-20.0, 0.0]","[None, 0.0]"
R_2OMXYLtex_M_Bacteroides_ovatus_ATCC_8483,"[-20.0, 0.0]","[None, 0.0]"
R_3HAD140_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.46156233646257494]","[0.0, 0.0]"
R_ACHBPL_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 4.483444657915389]","[0.0, 0.0]"
R_ACPS1_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.12391793557313138]","[0.0, 0.0]"
R_ACtex_M_Bacteroides_ovatus_ATCC_8483,"[-3232707.5394736803, 10.0]","[None, 7570735.096153891]"
R_ADNCNT3tcpp_M_Bacteroides_ovatus_ATCC_8483,"[-122.00000000314321, 10.0]","[None, 112.00000000000003]"
R_ADNCYC_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"
R_ADNtex_M_Bacteroides_ovatus_ATCC_8483,"[-122.00000000314321, 10.0]","[None, 112.00000000000001]"
R_ADOCBIK_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"
R_ADOCBIK2_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"
R_ADOCBLS_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"
R_ADOCBLabcpp_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 4332498.605769235]","[None, 4362072.01923077]"
R_ADOCBLtex_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 4332498.605769235]","[None, 4362072.019230736]"
R_ADPRDP_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"
R_ADPT_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 3225632.6842948664]","[None, 3245782.820512812]"
R_ADSELK_M_Bacteroides_ovatus_ATCC_8483,"[0.0, 0.0]","[None, 0.0]"

In [ ]:
different_sol_df[different_sol_df.index.str.contains("_DM_M|sink")]

,m1+m2,merged
R_gthrd_sink_M_Bacteroides_thetaiotaomicron_VPI_5482,"[-0.06788787374385921, 0.0]","[0.0, 0.0]"
R_thissh_sink_M_Bacteroides_thetaiotaomicron_VPI_5482,"[-0.06788787374370793, 0.0]","[0.0, 0.0]"
R_4hba_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374381214]","[0.0, 0.0]"
R_this_DM_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.0678878737432866]","[0.0, 0.0]"

In [ ]:
for rxn in different_sol_df[different_sol_df.index.str.contains("_DM_M|sink")].index:
    print(comm.merged_model.reactions[rxn])
    external = comm.merged_model.reactions[rxn].get_products()[0]
    cytosolic = comm.merged_model.reactions[rxn].get_substrates()[0]
    
    print(f"\t external reactions:{comm.merged_model.get_metabolite_reactions(external)}\n")
    print(f"\t cytosolic reactions:{comm.merged_model.get_metabolite_reactions(cytosolic)}\n")

R_gthrd_sink_M_Bacteroides_thetaiotaomicron_VPI_5482: M_gthrd__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482 <-> M_gthrd__91__e__93__
	 external reactions:['R_gthrd_sink_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_EX_gthrd__91__e__93__']

	 cytosolic reactions:['R_LGTHL_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_biomass345_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_gthrd_sink_M_Bacteroides_thetaiotaomicron_VPI_5482']

R_thissh_sink_M_Bacteroides_thetaiotaomicron_VPI_5482: M_thissh__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482 <-> M_thissh__91__e__93__
	 external reactions:['R_thissh_sink_M_Bacteroides_ovatus_ATCC_8483', 'R_thissh_sink_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_EX_thissh__91__e__93__']

	 cytosolic reactions:['R_DXYTST_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_thissh_sink_M_Bacteroides_thetaiotaomicron_VPI_5482']

R_4hba_DM_M_Bacteroides_thetaiotaomicron_VPI_5482: M_4hba__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482 --> M_4hba__91__e__93__
	 external reactions:['R_4hba_DM_M_Bacteroides_ovatus_ATCC_8483', 'R_4hba_DM_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_EX_4hba__91__e__93__']

	 cytosolic reactions:['R_THZPSN_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_4hba_DM_M_Bacteroides_thetaiotaomicron_VPI_5482']

R_this_DM_M_Bacteroides_thetaiotaomicron_VPI_5482: M_this__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482 --> M_this__91__e__93__
	 external reactions:['R_this_DM_M_Bacteroides_ovatus_ATCC_8483', 'R_this_DM_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_EX_this__91__e__93__']

	 cytosolic reactions:['R_DXYTST_M_Bacteroides_thetaiotaomicron_VPI_5482', 'R_this_DM_M_Bacteroides_thetaiotaomicron_VPI_5482']

**Find essential reactions**

In [ ]:
essential_m2 = []

for rxn in model2.reactions:
    knockout = reframed.reaction_knockout(model2,[rxn])
    
    if knockout.fobj<1e-6:
        essential_m2.append(rxn)

In [ ]:
different_sol_df[ (different_sol_df.index.isin([rxn+"_"+model2.id for rxn in essential_m2]))]

,m1+m2,merged
R_ACBIPGT_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374373186]","[0.0, 0.0]"
R_ACPS1_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374373276]","[0.0, 0.0]"
R_ADCL_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.20366362123014925]","[0.0, 0.0]"
R_ADCS_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.20366362123014925]","[0.0, 0.0]"
R_ADK2_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374338304]","[0.0, 0.0]"
...,...,...
R_ZN2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787373807281]","[0.0, 0.0]"
R_r0339_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.10183181061537483]","[0.0, 0.0]"
R_r2137pp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374374732]","[0.0, 0.0]"
R_biomass345_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 21.92406708987959]","[0.0, 0.0]"
R_gthrd_sink_M_Bacteroides_thetaiotaomicron_VPI_5482,"[-0.06788787374385921, 0.0]","[0.0, 0.0]"

In [ ]:
transport_m2 = [rxn+"_"+model2.id for rxn in model2.get_reactions_by_type(reframed.ReactionType.TRANSPORT)]

different_sol_df[ (different_sol_df.index.isin([rxn+"_"+model2.id for rxn in essential_m2])) & (different_sol_df.index.isin(transport_m2))]

,m1+m2,merged
R_CA2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374383126]","[0.0, 0.0]"
R_CAt4ipp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374393003]","[0.0, 0.0]"
R_CLtex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374194899]","[0.0, 0.0]"
R_COBALT2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374367752]","[0.0, 0.0]"
R_COBALTt5pp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[-0.06788787374387625, 0.0]","[0.0, 0.0]"
R_CU2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374358193]","[0.0, 0.0]"
R_FE2abcpp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.20349093914124194]","[0.0, 0.0]"
R_FE2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.20349093914124194]","[0.0, 0.0]"
R_HEMEtipp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374363149]","[0.0, 0.0]"
R_Ktex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787373807281]","[0.0, 0.0]"
R_LYS_Ltex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 6.258005710113849]","[0.0, 0.0]"
R_LYSt3rpp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[-6.258005710124324, 0.0]","[0.0, 0.0]"
R_MG2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787373807281]","[0.0, 0.0]"
R_MN2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.0678878737436803]","[0.0, 0.0]"
R_MNt2pp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374363096]","[0.0, 0.0]"
R_PHEMEtex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374369228]","[0.0, 0.0]"
R_PRO_Ltex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 10.0]","[0.0, None]"
R_Q8abcpp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374365406]","[0.0, 0.0]"
R_Q8tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374365406]","[0.0, 0.0]"
R_SO4t2pp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.067887873743436]","[0.0, 0.0]"
R_SPMDabcpp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.067887873743436]","[0.0, 0.0]"
R_SPMDtex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.067887873743436]","[0.0, 0.0]"
R_ZN2tex_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787373807281]","[0.0, 0.0]"
R_r2137pp_M_Bacteroides_thetaiotaomicron_VPI_5482,"[0.0, 0.06788787374374732]","[0.0, 0.0]"

In [ ]:
set(met_one_reaction).intersection(set([rxn+"_"+model2.id for rxn in essential_m2]))

{'R_biomass345_M_Bacteroides_thetaiotaomicron_VPI_5482'}

In [ ]:
[rxn for rxn in comm.merged_model.reactions if "biomass" in rxn]

['R_biomass536_M_Bacteroides_ovatus_ATCC_8483',
 'R_biomass345_M_Bacteroides_thetaiotaomicron_VPI_5482']

In [ ]:
comm.merged_model.biomass_reaction

'community_growth'

In [ ]:
interesting_reactions = different_sol_df[ (different_sol_df.index.isin([rxn+"_"+model2.id for rxn in essential_m2]))].index

blocked_reactions_manip = {}
checked_met = []
for rxn in interesting_reactions:
    mets = comm.merged_model.reactions[rxn].get_substrates()

    for met in mets:
        if met in checked_met:
            continue
            
        print(met)
        checked_met.append(met)
        temp_model = comm.merged_model.copy()
        temp_model.add_reaction_from_str(f"R_{met[2:]}_extra_sink: met <->")

M_adocbip__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gtp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_h__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_apoACP__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_coa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_4adcho__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_chor__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gln_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_amp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pppi__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_adocbi__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_agdpcbi__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_rdmbzi__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_adphep_DD__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ala_D__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_atp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ala_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gly__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_succoa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_air__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_h2o__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_nad__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_5apru__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_nadph__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_asp_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_prpp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pap__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ca2__91__e__93__
M_ca2__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cbi__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cl__91__e__93__
M_cobalt2__91__e__93__
M_cobalt2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cu2__91__e__93__
M_ru5p_D__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dhpt__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_glu_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_25dhpp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dpcoa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_2dhp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dtmp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_nadh__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_tdec2eACP__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_kdo2lipid4L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_myrsACP__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_fe2__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_fe2__91__e__93__
M_fmn__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_frdp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ipdp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dttp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_g1p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gicolipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_udpg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gcald__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_icolipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gagicolipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ggagicolipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_glu_D__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_glx__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_glyclt__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gmhep1p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gmhep7p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gmhep17bp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pheme__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_hhlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_hphhlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_adphep_LD__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_lipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_hlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_phhlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gggagicolipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ppbng__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_akg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ile_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ttc_ggdp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ACP__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ivcoa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_k__91__e__93__
M_lys_L__91__e__93__
M_h__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_lys_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_mg2__91__e__93__
M_mn2__91__e__93__
M_mn2__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ckdo__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_phphhlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_3mob__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_mlthf__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_nicrnt__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dmbzid__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ala_B__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pant_R__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_udcpp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ugmda__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_PGPm1__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uaagmda__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pheme__91__e__93__
M_5aprbu__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_4ampm__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pnto_R__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_5aop__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_4ppcys__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pro_L__91__e__93__
M_ps180__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_psai17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_psi17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cdpdodecg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ser_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cdpdaihpdecg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cdpdihpdecg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pan4p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_q8__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_q8__91__e__93__
M_ribflv__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_4r5au__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_db4p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dmlz__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dtdprmn__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_kphphhlipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_5prdmbz__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_s7p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dscl__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_fe2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_scl__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_so4__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_spmd__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_spmd__91__e__93__
M_dtdp4d6dg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dtdp4d6dm__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dtdpglu__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_thmmp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_2h3oppan__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_26dap_M__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uamag__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pep__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uacgam__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uagmda__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uama__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uamr__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uaccg__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_udcpdp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_alaala__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ugmd__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_amet__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_uppg3__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_hmbil__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_zn2__91__e__93__
M_glyc_R__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cl__91__p__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_10fthf__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_2dmmq8__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_5mthf__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_PGP__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_adocbl__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_arg_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_asn_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ca2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cl__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_clpn180__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_clpnai17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_clpni17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_colipa__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ctp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cu2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_cys_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_datp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dctp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dgtp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_dnarep__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_fad__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_fe3__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_gthrd__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_his_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_k__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_leu_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_met_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_mg2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_mn2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_mqn8__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_nadp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pe180__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_peai17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pei17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pg180__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pgai17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pgi17__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_phe_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pheme__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pro_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_proteinsynth__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_ptrc__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_pydx5p__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_q8__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_rnatrans__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_sheme__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_so4__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_spmd__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_thf__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_thmpp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_thr_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_trp_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_tyr_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_utp__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_val_L__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482
M_zn2__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482

In [ ]:
temp_model.get_metabolite_reactions("M_proteinsynth__91__c__93___M_Bacteroides_thetaiotaomicron_VPI_5482")

['R_biomass345_M_Bacteroides_thetaiotaomicron_VPI_5482']

In [ ]:
model2.get_metabolite_reactions("M_proteinsynth__91__c__93__")

['R_pbiosynthesis', 'R_biomass345']

In [ ]:
model2.reactions.R_pbiosynthesis

R_pbiosynthesis:  <-> M_proteinsynth__91__c__93__ [-10.0, inf]

In [ ]:
[rxn for rxn in temp_model.reactions if "R_pbiosyn" in rxn]

[]

In [ ]:
"R_pbiosynthesis" in model2.get_exchange_reactions()

True

**Example of a CarveMe model**

In [ ]:
model_test = reframed.load_cbmodel("../../Ruminiclostridium_cellulolyticum_model/Ruminiclostridium-cellullolyticum-model-final/models/RcH10_final.xml")

In [ ]:
model_test.reactions.R_Growth

R_Growth: 0.000223 M_10fthf_c + 0.513689 M_ala__L_c + 0.000223 M_amet_c + 0.295792 M_arg__L_c + 0.241055 M_asn__L_c + 0.241055 M_asp__L_c + 29.54 M_atp_c + 0.005205 M_ca2_c + 0.005205 M_cl_c + 0.000576 M_coa_c + 0.0001 M_cobalt2_c + 0.133508 M_ctp_c + 0.000709 M_cu2_c + 0.09158 M_cys__L_c + 0.026166 M_datp_c + 0.027017 M_dctp_c + 0.027017 M_dgtp_c + 0.026166 M_dttp_c + 0.000223 M_fad_c + 0.006715 M_fe2_c + 0.007808 M_fe3_c + 0.26316 M_gln__L_c + 0.26316 M_glu__L_c + 0.612638 M_gly_c + 0.001 M_gtca1_45_BS_c + 0.001 M_gtca2_45_BS_c + 0.001 M_gtca3_45_BS_c + 0.215096 M_gtp_c + 48.601527 M_h2o_c + 0.094738 M_his__L_c + 0.290529 M_ile__L_c + 0.195193 M_k_c + 0.450531 M_leu__L_c + 5e-05 M_lipo1_24_BS_c + 5e-05 M_lipo2_24_BS_c + 5e-05 M_lipo3_24_BS_c + 5e-05 M_lipo4_24_BS_c + 0.343161 M_lys__L_c + 0.153686 M_met__L_c + 0.008675 M_mg2_c + 0.000223 M_mlthf_c + 0.000691 M_mn2_c + 0.0001 M_mql8_c + 0.001831 M_nad_c + 0.000447 M_nadp_c + 0.01 M_peptido_BS_c + 0.185265 M_phe__L_c + 0.221055 M_pro__L_c + 0.000223 M_pydx5p_c + 0.000223 M_ribflv_c + 0.215792 M_ser__L_c + 0.004338 M_so4_c + 0.000223 M_thf_c + 0.000223 M_thmpp_c + 0.253687 M_thr__L_c + 0.056843 M_trp__L_c + 0.137896 M_tyr__L_c + 0.144104 M_utp_c + 0.423162 M_val__L_c + 0.000341 M_zn2_c --> 29.54 M_adp_c + 29.54 M_h_c + 29.54 M_pi_c + 0.773903 M_ppi_c @1.0

In [ ]:
sol = SteadierCom(community, abundance=abundance, growth=growth, allocation=True, constraints=env, w_e=w_e, w_r=w_r, objective=target)

(-10.0, inf)