# Check convergence

In [1]:
import cobra
import pandas as pd
import numpy as np
import scipy
import warnings
import seaborn as sns
from collections import OrderedDict
from os import listdir
import matplotlib.pyplot as plt

from reframed.community.model import Community
from reframed import Environment, set_default_solver
from steadiercom.cli import load_communities,load_media_db

import sys
sys.path.append("../functions/")
from simulation.convergence import SteadierSampleConvergence
from simulation.convergence import std_sample_size,std_sampling_grouped,std_sampling_grouped_freq
sys.path.append("../scripts_python")
import convergence_test_script

In [2]:
from IPython.display import HTML, display
import os
from IPython.display import display, HTML

In [3]:

display(HTML("<style>body { background: rgb(247, 247, 247) !important; }</style>"))

In [4]:
%load_ext autoreload
%autoreload 2

### Gut microbiome community

Concentration $X_0$ (right after serial transfer) and $X_1$ (right before next transfer) in $t_0$ and $t_1$

$$
X_1 = X_0 *e^{\mu t_1} , X_0 = X_0
$$

Assuming that the cells grow back to the original concentration (after being diluted 1:20 => the cells increase in density by 20 times)

$$
X_1/X_0 = 21 = e^{\mu t} 
$$

The above equation turns into:
$$
ln(X_1/X_0) = \mu t
$$

Which means the avearage growth rate becomes
$$
\mu_{avg} = \frac{ln(20)}{t}
$$

**Methods (From Venturelli et al. 2018): 1:20 dilution every 24 h**

In [5]:
np.log(20)/24

np.float64(0.12482217806474961)

In [6]:
mediadb = "../data/Venturelli2018/generated/media_db.tsv"#path to mediadb
medium = "LB_extend"
growth = np.log(20)/24# average growth rate

models = ["../models/Venturelli2018/species_used_noO2/"+name for name in listdir("../models/Venturelli2018/species_used_noO2/")]
communities = "../data/Venturelli2018/generated/communities_steadiercom_no_abundance/NONE_abundance.tsv"

comm_id = "NONE"

output_dir = "../output/Venturelli2018/convergence_test_no_abundance/"

%%time

abstol = 1e-6
model_cache, comm_dict, has_abundance = load_communities(models, communities, exchange_detection='R_EX_(?!biomass__40__e__41__)')

media_db, media_has_bounds = load_media_db(mediadb)
results = []

organisms = comm_dict[comm_id]

comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
community = Community(comm_id, comm_models, copy_models=False)

env = Environment.from_reactions(media_db[medium],max_uptake=10)
env.apply(community.merged_model, inplace=False, exclusive=True, warning=False)
env_dict = dict(env)

print(f'simulating {comm_id} in {medium} medium')

sol_df = SteadierSampleConvergence(community,output_dir=output_dir,n=20001, growth=growth, allocation=True, constraints=env)

In [7]:
dfs_tot, dfs_tot_abs = convergence_test_script.load_data_and_preprocess(output_dir)

INFO     | Loading data from ../output/Venturelli2018/convergence_test_no_abundance/...

In [8]:

results = convergence_test_script.process_data(dfs_tot_abs)

INFO     | Processing data (finding standard deviation and coefficient of variance)...

250
500
1000
2000
4000
8000
500
1000
1500
2000
2500
3000
3500
4000
4500
5000

In [9]:
convergence_test_script.make_report(results,output_dir)

INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
/Users/idunmariaburgos/opt/anaconda3/envs/steadiercom/lib/python3.10/site-packages/pandas/core/algorithms.py:1743: RuntimeWarning: divide by zero encountered in log10
  return lib.map_infer(values, mapper, convert=convert)

In [10]:


html_path = os.path.join("html_reports/Venturelli2018/", output_dir.split("/")[-2], "report.html")
display(HTML(filename=html_path))

## E.coli mutants community

Concentration $X_0$ (right after serial transfer) and $X_1$ (right before next transfer) in $t_0$ and $t_1$

$$
X_1 = X_0 *e^{\mu t_1} , X_0 = X_0
$$

Assuming that the cells grow back to the original concentration (after being diluted 5:995 => has to increase 200 times)

$$
X_1/X_0 = 200 = e^{\mu t} 
$$

The above equation turns into:
$$
ln(X_1/X_0) = \mu t
$$

Which means the avearage growth rate becomes
$$
\mu_{avg} = \frac{ln(200)}{t}
$$

**Methods (From Guillen et al. 2021): 1:200 dilution every 24 h**

In [11]:
np.log(200)/24

np.float64(0.22076322360616818)

**Input data**

In [12]:
mediadb = "../data/Guillen2021/generated/media_db.tsv"#path to mediadb
medium = "M9"
growth = np.log(200)/24 

models = ["../models/Guillen2021/top_7_strains/"+name for name in listdir("../models/Guillen2021/top_7_strains/")]
communities = "../data/Guillen2021/generated/communities_smetana.tsv"

comm_id = "ecoli_auxotrophs"

output_dir = "../output/Guillen2021/convergence_test_no_abundance/"

**Run SteadierSample**

%%time

abstol = 1e-6
model_cache, comm_dict, has_abundance = load_communities(models, communities, exchange_detection='^R_EX_(?!nad_c$|thf_c$).*')


media_db, media_has_bounds = load_media_db(mediadb)
results = []

organisms = comm_dict[comm_id]

comm_models = [model_cache.get_model(org_id, reset_id=True) for org_id in organisms]
community = Community(comm_id, comm_models, copy_models=False)

env = Environment.from_compounds(media_db[medium],max_uptake=10)
env.apply(community.merged_model, inplace=False, exclusive=True, warning=False)
env_dict = dict(env)

print(f'simulating {comm_id} in {medium} medium')

sol_df = SteadierSampleConvergence(community,output_dir=output_dir,n=20001, growth=growth, allocation=True, constraints=env)

In [13]:
dfs_tot, dfs_tot_abs = convergence_test_script.load_data_and_preprocess(output_dir)

INFO     | Loading data from ../output/Guillen2021/convergence_test_no_abundance/...

In [14]:

results = convergence_test_script.process_data(dfs_tot_abs)

INFO     | Processing data (finding standard deviation and coefficient of variance)...

250
500
1000
2000
4000
8000
500
1000
1500
2000
2500
3000
3500
4000
4500
5000

In [15]:
convergence_test_script.make_report(results,output_dir,ecoli_or_gut="Guillen2021")

INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
INFO     | Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
/Users/idunmariaburgos/opt/anaconda3/envs/steadiercom/lib/python3.10/site-packages/pandas/core/algorithms.py:1743: RuntimeWarning: divide by zero encountered in log10
  return lib.map_infer(values, mapper, convert=convert)

In [16]:
import os
from IPython.display import display, HTML

html_path = os.path.join("html_reports/Guillen2021/", output_dir.split("/")[-2], "report.html")
display(HTML(filename=html_path))